name: CI tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: python -m pip install poetry
    - name: Install application
      run: poetry install
    - name: Test with pytest
      run: poetry run pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install application
        run: poetry install
      - name: Check for flake8 issues
        run: poetry run flake8 .
      - name: Check code formatting with Black
        run: poetry run tan . --check
      - name: Check import ordering with isort
        run: poetry run isort . --check --diff

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install application
        run: poetry install
      - name: Check using mypy
        run: poetry run mypy bna
